// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/ktp/pending": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengembalikan semua pengajuan verifikasi KTP dengan status 'pending'. Endpoint ini memerlukan role admin.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Ambil daftar verifikasi KTP yang menunggu review",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.SuccessEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/admin/ktp/{user_id}/review": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin menyetujui, menolak, atau meminta pengiriman ulang dokumen KTP pengguna. Endpoint ini memerlukan role admin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Review pengajuan verifikasi KTP pengguna",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID pengguna (UUID)",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Keputusan review",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.ReviewVerificationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.SuccessEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/auth/google": {
            "post": {
                "description": "Menerima access token dari Supabase (hasil login Google), memverifikasi token, lalu mengembalikan JWT app. User harus sudah terdaftar di mst_users dengan ID yang sama dengan sub claim token Supabase.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login menggunakan Google via Supabase",
                "parameters": [
                    {
                        "description": "Access token dari Supabase",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.GoogleLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/docs.SuccessEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_auth.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/auth/ktp/upload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menerima dua file gambar: foto KTP dan foto selfie. Batas ukuran masing-masing 10MB. Setelah upload, status verifikasi menjadi 'pending' hingga direview admin.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Upload foto KTP dan selfie untuk verifikasi identitas",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Foto KTP (max 10MB)",
                        "name": "ktp_photo",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Foto selfie dengan KTP (max 10MB)",
                        "name": "selfie_photo",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/docs.SuccessEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_auth.KTPUploadResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Autentikasi pengguna menggunakan nomor telepon dan password. Mengembalikan JWT Bearer Token yang berlaku 7 hari.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login pengguna",
                "parameters": [
                    {
                        "description": "Kredensial login",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/docs.SuccessEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_auth.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengembalikan data profil lengkap pengguna yang sedang login berdasarkan JWT token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Ambil profil pengguna saat ini",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.SuccessEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Membuat akun pengguna baru dengan role worker atau employer. Token JWT langsung dikembalikan setelah registrasi berhasil.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Registrasi pengguna baru",
                "parameters": [
                    {
                        "description": "Data registrasi",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/docs.SuccessEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_auth.RegisterResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/auth/roles/activate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menambahkan role baru (worker atau employer) ke akun pengguna. Mengembalikan token JWT baru yang mencerminkan role aktif.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Aktifkan role baru untuk pengguna",
                "parameters": [
                    {
                        "description": "Role yang ingin diaktifkan",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.ActivateRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.SuccessEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/auth/roles/switch": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengganti konteks role aktif pengguna. Pengguna harus sudah mengaktifkan role tersebut sebelumnya. Mengembalikan token JWT baru.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Ganti role aktif pengguna",
                "parameters": [
                    {
                        "description": "Role yang ingin diaktifkan",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.SwitchRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.SuccessEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/auth/worker/toggle": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengubah status ketersediaan worker (aktif/tidak aktif) beserta koordinat GPS terkini.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Toggle status aktif worker",
                "parameters": [
                    {
                        "description": "Status dan koordinat GPS",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.ToggleWorkerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.SuccessEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/jobs": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Employer membuat permintaan pekerjaan. Sistem akan menjalankan MatchingEngine untuk menemukan maksimal 3 kandidat worker berdasarkan GPS, skor, dan keahlian.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "Buat pekerjaan baru",
                "parameters": [
                    {
                        "description": "Data pekerjaan",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_job.CreateJobRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/docs.SuccessEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_job.CreateJobResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/jobs/employer": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengembalikan daftar pekerjaan yang dibuat oleh employer yang sedang login, dengan opsi filter status dan paginasi.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "Ambil daftar pekerjaan milik employer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter status pekerjaan (contoh: matched, done, cancelled)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Halaman (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Jumlah per halaman (default: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.SuccessEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/jobs/worker": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengembalikan daftar pekerjaan yang terhubung dengan worker yang sedang login, dengan opsi filter status dan paginasi.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "Ambil daftar pekerjaan untuk worker",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter status pekerjaan (contoh: accepted, done)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Halaman (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Jumlah per halaman (default: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.SuccessEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/jobs/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengembalikan detail lengkap sebuah pekerjaan termasuk status, kandidat, dan informasi pekerja yang diterima.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "Ambil detail pekerjaan berdasarkan ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.SuccessEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/jobs/{id}/accept-match": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Worker menerima tawaran match dari employer. Hanya satu worker yang bisa menerima per job. Jika job sudah diambil worker lain, akan dikembalikan error 409.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "Worker menerima tawaran pekerjaan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Match ID yang diterima",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_job.AcceptMatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.SuccessEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "409": {
                        "description": "JOB_TAKEN — job sudah diterima worker lain",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/jobs/{id}/arrive": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Worker mengirimkan koordinat GPS saat tiba di lokasi. Sistem memverifikasi jarak terhadap lokasi job. Jika terlalu jauh, dikembalikan error 422 dengan kode GPS_TOO_FAR.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "Worker menandai kedatangan di lokasi pekerjaan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Koordinat GPS saat tiba",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_job.ArriveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.SuccessEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "422": {
                        "description": "GPS_TOO_FAR — lokasi terlalu jauh dari titik pekerjaan",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/jobs/{id}/complete": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Worker mengunggah bukti foto penyelesaian pekerjaan via PATCH. Minimal 1 foto wajib diunggah, total maksimal 20MB.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "Tandai pekerjaan selesai — PATCH (worker)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Foto bukti pekerjaan (minimal 1)",
                        "name": "proof_photos[]",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Catatan penyelesaian",
                        "name": "notes",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/docs.SuccessEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_job.CompleteJobResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/jobs/{id}/confirm": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Employer mengkonfirmasi bahwa pekerjaan telah selesai dikerjakan. Dana escrow dilepaskan ke worker setelah konfirmasi.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "Employer mengkonfirmasi pekerjaan selesai",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.SuccessEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/jobs/{id}/match-fallback": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Memperluas pencarian kandidat ke seluruh kota ketika matching radius awal tidak menghasilkan kandidat yang cukup.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "Fallback matching ke level kota",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "City ID untuk fallback",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_job.MatchFallbackRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.SuccessEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/jobs/{id}/rate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Baik employer maupun worker dapat memberikan rating setelah pekerjaan selesai. Employer menilai worker, worker menilai employer. Skor 1.0–5.0 skala bintang.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "Beri rating untuk pekerjaan yang telah selesai",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Rating dan komentar",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_job.RateJobRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/docs.SuccessEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/jobs/{id}/reject-match": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Worker menolak match dari employer. Sistem akan otomatis memberitahu kandidat berikutnya jika ada.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "Worker menolak tawaran pekerjaan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Match ID yang ditolak",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_job.RejectMatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.SuccessEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/payments/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Employer membuat pembayaran escrow melalui Midtrans Snap. Logika platform fee: transaksi di bawah Rp 1.000.000 dikenakan flat Rp 10.000; transaksi Rp 1.000.000 ke atas dikenakan 2% dari agreed_price.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Buat pembayaran untuk job yang sudah diterima",
                "parameters": [
                    {
                        "description": "Job ID yang akan dibayar",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_payment.CreatePaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/docs.SuccessEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_payment.CreatePaymentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/payments/webhook": {
            "post": {
                "description": "Endpoint ini dipanggil otomatis oleh server Midtrans setelah transaksi berhasil atau gagal. Tidak memerlukan autentikasi JWT.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Webhook notifikasi pembayaran dari Midtrans",
                "parameters": [
                    {
                        "description": "Payload notifikasi Midtrans",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_payment.WebhookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.SuccessEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/payments/{job_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengembalikan detail pembayaran escrow untuk job tertentu, termasuk status escrow (pending, held, released, refunded), amount, platform_fee, dan net_to_worker.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Cek status pembayaran berdasarkan Job ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID (UUID)",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.SuccessEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/payments/{job_id}/milestones": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengembalikan array milestone pembayaran harian untuk job multi-hari (duration_days \u003e 1). Setiap milestone merepresentasikan pembayaran per hari yang dirilis secara bertahap setelah employer mengkonfirmasi penyelesaian hari tersebut.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Ambil daftar milestone pembayaran harian",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID (UUID)",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.SuccessEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/ref/rate-cards": {
            "get": {
                "description": "Mengembalikan harga min/max pasar untuk kategori skill tertentu di kota tertentu. Endpoint publik, tidak memerlukan autentikasi.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "Ambil rate card pasar untuk kategori skill dan kota",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID kategori skill",
                        "name": "skill_cat_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kode kota (contoh: JKT)",
                        "name": "city_code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/docs.SuccessEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_job.RateCardResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/ref/skill-categories": {
            "get": {
                "description": "Mengembalikan seluruh kategori skill yang tersedia di platform. Endpoint publik, tidak memerlukan autentikasi.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "Ambil daftar semua kategori skill",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/docs.SuccessEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "object",
                                                "additionalProperties": true
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/workers/{id}/score": {
            "get": {
                "description": "Mengembalikan KerjantaraScore (rata-rata rating 0.00–5.00) beserta riwayat perubahan skor. kerjantara_score dihitung sebagai rata-rata dari semua rating yang diterima pekerja dari tabel trx_ratings, diperbarui otomatis saat event job.rated diterima. Endpoint ini bersifat publik dan tidak memerlukan autentikasi.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Score"
                ],
                "summary": "Lihat skor reputasi pekerja",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Worker ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/docs.SuccessEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_score.WorkerScoreData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/ws": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Upgrade HTTP GET ke protokol WebSocket. JWT dikirim via query parameter ?token=\u003cjwt\u003e karena header Authorization tidak didukung saat WebSocket upgrade. Setelah koneksi berhasil, server mengirim pesan JSON: {\"type\":\"\u003cevent\u003e\",\"payload\":{...},\"timestamp\":\"\u003cRFC3339\u003e\"}. Event types: job.matched (notif ke worker saat job cocok), job.accepted (notif ke employer saat worker menerima), job.completed (notif dari worker ke employer untuk konfirmasi), job.completed (notif konfirmasi selesai), payment.released (notif ke worker saat pembayaran dilepas), ktp.uploaded (broadcast ke admin saat KTP diunggah). Koneksi otomatis ditutup jika token tidak valid (HTTP 401 sebelum upgrade).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notification"
                ],
                "summary": "Koneksi WebSocket untuk notifikasi real-time",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT Bearer Token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "Switching Protocols — WebSocket connection established",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorEnvelope"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "docs.ErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "VALIDATION_ERROR"
                },
                "message": {
                    "type": "string",
                    "example": "Field tidak valid"
                }
            }
        },
        "docs.ErrorEnvelope": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/docs.ErrorDetail"
                }
            }
        },
        "docs.MetaInfo": {
            "type": "object",
            "properties": {
                "timestamp": {
                    "type": "string",
                    "example": "2024-01-15T08:30:00+07:00"
                }
            }
        },
        "docs.SuccessEnvelope": {
            "type": "object",
            "properties": {
                "data": {},
                "meta": {
                    "$ref": "#/definitions/docs.MetaInfo"
                }
            }
        },
        "internal_auth.ActivateRoleRequest": {
            "type": "object",
            "properties": {
                "role": {
                    "type": "string",
                    "example": "worker"
                }
            }
        },
        "internal_auth.GoogleLoginRequest": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "internal_auth.KTPUploadResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "KTP berhasil diupload, menunggu review"
                },
                "verif_status": {
                    "type": "string",
                    "example": "pending"
                }
            }
        },
        "internal_auth.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "P@ssw0rd123"
                },
                "phone": {
                    "type": "string",
                    "example": "081234567890"
                }
            }
        },
        "internal_auth.LoginResponse": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string",
                    "example": "Budi Santoso"
                },
                "role": {
                    "type": "string",
                    "example": "worker"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "token_expires_at": {
                    "type": "string",
                    "example": "2024-01-15T09:30:00+07:00"
                },
                "user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "verif_status": {
                    "type": "string",
                    "example": "unverified"
                }
            }
        },
        "internal_auth.RegisterRequest": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string",
                    "example": "Budi Santoso"
                },
                "password": {
                    "type": "string",
                    "example": "P@ssw0rd123"
                },
                "phone": {
                    "type": "string",
                    "example": "081234567890"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "worker",
                        "employer"
                    ],
                    "example": "worker"
                }
            }
        },
        "internal_auth.RegisterResponse": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string",
                    "example": "Budi Santoso"
                },
                "role": {
                    "type": "string",
                    "example": "worker"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "internal_auth.ReviewVerificationRequest": {
            "type": "object",
            "properties": {
                "decision": {
                    "type": "string",
                    "enum": [
                        "approved",
                        "rejected",
                        "resubmit"
                    ],
                    "example": "approved"
                },
                "note": {
                    "type": "string",
                    "example": "KTP terlihat jelas dan valid"
                }
            }
        },
        "internal_auth.SwitchRoleRequest": {
            "type": "object",
            "properties": {
                "role": {
                    "type": "string",
                    "example": "employer"
                }
            }
        },
        "internal_auth.ToggleWorkerRequest": {
            "type": "object",
            "properties": {
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "lat": {
                    "type": "number",
                    "example": -6.2088
                },
                "lng": {
                    "type": "number",
                    "example": 106.8456
                }
            }
        },
        "internal_job.AcceptMatchRequest": {
            "type": "object",
            "properties": {
                "match_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "internal_job.ArriveRequest": {
            "type": "object",
            "properties": {
                "lat": {
                    "type": "number",
                    "example": -6.2088
                },
                "lng": {
                    "type": "number",
                    "example": 106.8456
                }
            }
        },
        "internal_job.CandidateItem": {
            "type": "object",
            "properties": {
                "avg_response_min": {
                    "type": "number",
                    "example": 5.2
                },
                "bio": {
                    "type": "string",
                    "example": "Tukang las berpengalaman 10 tahun"
                },
                "composite_score": {
                    "type": "number",
                    "example": 0.96
                },
                "distance_km": {
                    "type": "number",
                    "example": 1.5
                },
                "full_name": {
                    "type": "string",
                    "example": "Budi Santoso"
                },
                "kerjantara_score": {
                    "type": "number",
                    "example": 4.8
                },
                "match_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "match_rank": {
                    "type": "integer",
                    "example": 1
                },
                "response_deadline": {
                    "type": "string",
                    "example": "2024-01-15T08:45:00+07:00"
                },
                "total_jobs_done": {
                    "type": "integer",
                    "example": 42
                },
                "worker_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                }
            }
        },
        "internal_job.CompleteJobResponse": {
            "type": "object",
            "properties": {
                "job_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440002"
                },
                "message": {
                    "type": "string",
                    "example": "Menunggu konfirmasi pemberi kerja"
                },
                "proof_file_keys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "proof_photo_urls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "done"
                }
            }
        },
        "internal_job.CreateJobRequest": {
            "type": "object",
            "properties": {
                "budget": {
                    "type": "integer",
                    "example": 500000
                },
                "city_code": {
                    "type": "string",
                    "example": "JKT"
                },
                "description": {
                    "type": "string",
                    "example": "Butuh tukang las untuk pagar rumah"
                },
                "lat": {
                    "type": "number",
                    "example": -6.2088
                },
                "lng": {
                    "type": "number",
                    "example": 106.8456
                },
                "skill_cat_id": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "internal_job.CreateJobResponse": {
            "type": "object",
            "properties": {
                "budget": {
                    "type": "integer",
                    "example": 500000
                },
                "budget_vs_market": {
                    "type": "string",
                    "example": "within_range"
                },
                "candidates": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_job.CandidateItem"
                    }
                },
                "job_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440002"
                },
                "rate_card": {
                    "$ref": "#/definitions/internal_job.RateCardResponse"
                },
                "response_window_minutes": {
                    "type": "integer",
                    "example": 15
                },
                "status": {
                    "type": "string",
                    "example": "matched"
                }
            }
        },
        "internal_job.MatchFallbackRequest": {
            "type": "object",
            "properties": {
                "city_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_job.RateCardResponse": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string",
                    "example": "Harga wajar Tukang Las di JKT: Rp 300000 – 700000/hari"
                },
                "max_rate": {
                    "type": "integer",
                    "example": 700000
                },
                "min_rate": {
                    "type": "integer",
                    "example": 300000
                },
                "rate_unit": {
                    "type": "string",
                    "example": "per_day"
                }
            }
        },
        "internal_job.RateJobRequest": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string",
                    "example": "Pekerja sangat profesional dan tepat waktu"
                },
                "score": {
                    "type": "number",
                    "example": 4.5
                }
            }
        },
        "internal_job.RejectMatchRequest": {
            "type": "object",
            "properties": {
                "match_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "internal_payment.CreatePaymentRequest": {
            "type": "object",
            "properties": {
                "job_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "internal_payment.CreatePaymentResponse": {
            "type": "object",
            "properties": {
                "agreed_price": {
                    "type": "integer",
                    "example": 500000
                },
                "fee_note": {
                    "type": "string",
                    "example": "Biaya layanan Rp 10.000 (transaksi di bawah Rp 1.000.000)"
                },
                "midtrans_order_id": {
                    "type": "string",
                    "example": "order-550e8400-1234"
                },
                "net_to_worker": {
                    "type": "integer",
                    "example": 490000
                },
                "payment_id": {
                    "type": "string",
                    "example": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                },
                "platform_fee": {
                    "type": "integer",
                    "example": 10000
                },
                "snap_token": {
                    "type": "string",
                    "example": "snap-token-abc123"
                },
                "total_charged_to_employer": {
                    "type": "integer",
                    "example": 500000
                }
            }
        },
        "internal_payment.WebhookRequest": {
            "type": "object",
            "properties": {
                "fraud_status": {
                    "type": "string",
                    "example": "accept"
                },
                "order_id": {
                    "type": "string",
                    "example": "order-550e8400-1234"
                },
                "transaction_status": {
                    "type": "string",
                    "example": "settlement"
                }
            }
        },
        "internal_score.ScoreHistoryItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "delta": {
                    "type": "number"
                },
                "job_id": {
                    "type": "string"
                },
                "score_after": {
                    "type": "number"
                },
                "score_before": {
                    "type": "number"
                }
            }
        },
        "internal_score.WorkerScoreData": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string"
                },
                "history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_score.ScoreHistoryItem"
                    }
                },
                "kerjantara_score": {
                    "type": "number"
                },
                "total_jobs_done": {
                    "type": "integer"
                },
                "worker_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Masukkan token JWT dalam format: Bearer \u003ctoken\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v3.3-hackathon",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Kerjantara Backend API",
	Description:      "Backend monolith modular untuk platform jasa informal Kerjantara.id. API ini menghubungkan employer dengan worker melalui matching engine berbasis GPS dan skor reputasi.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
